#! /usr/bin/env python
# -*- coding: utf-8 -*-
####################
# Shelly TRV - Indigo Plugin
# Auto-generated by Indigo Plugin Factory
####################

import json
import queue
import time
from datetime import datetime

import indigo

try:
    from mqtt_handler import ThreadMqttHandler, PAHO_AVAILABLE
except ImportError:
    PAHO_AVAILABLE = False

from discovery import EquipmentDiscovery
from handlers import thermostat_handler, sensor_handler

DEVICE_TYPE_MAP = {
    "thermostat": ("shellyThermostat", "equipmentId"),
    "sensor": ("shellySensor", "equipmentId")
}


class Plugin(indigo.PluginBase):

    def __init__(self, pluginId, pluginDisplayName, pluginVersion, pluginPrefs, **kwargs):
        super().__init__(pluginId, pluginDisplayName, pluginVersion, pluginPrefs, **kwargs)
        self.debug = pluginPrefs.get("showDebugInfo", False)
        self.logMqtt = pluginPrefs.get("logMqtt", False)
        self.deviceFolderId = int(pluginPrefs.get("deviceFolder", 0))

        self.coordinators = {}
        self.device_coordinator_map = {}
        self.discovery = EquipmentDiscovery(logger=self.logger)

    # -------------------------------------------------------------------------
    # Plugin lifecycle
    # -------------------------------------------------------------------------

    def startup(self):
        self.logger.info("Shelly TRV starting")
        if not PAHO_AVAILABLE:
            self.logger.error(
                "paho-mqtt library not found. Ensure it is in the plugin's Packages/ directory."
            )
            return

        coordinator_exists = False
        for dev in indigo.devices.iter("self.shellyController"):
            coordinator_exists = True
            break

        if not coordinator_exists:
            self._create_coordinator_device()

    def shutdown(self):
        self.logger.info("Shelly TRV stopping")
        for dev_id in list(self.coordinators.keys()):
            self._stop_coordinator(dev_id)

    def runConcurrentThread(self):
        try:
            while True:
                for dev_id, coord in list(self.coordinators.items()):
                    self._drain_queue(dev_id, coord["queue"])
                self.sleep(0.1)
        except self.StopThread:
            pass

    # -------------------------------------------------------------------------
    # Device lifecycle
    # -------------------------------------------------------------------------

    def deviceStartComm(self, dev):
        if dev.deviceTypeId == "shellyController":
            self._start_coordinator(dev)
        else:
            controller_id = dev.pluginProps.get("controllerId", "")
            if controller_id:
                self.device_coordinator_map[dev.id] = int(controller_id)

    def deviceStopComm(self, dev):
        if dev.deviceTypeId == "shellyController":
            self._stop_coordinator(dev.id)
        else:
            self.device_coordinator_map.pop(dev.id, None)

    # -------------------------------------------------------------------------
    # Preferences
    # -------------------------------------------------------------------------

    def closedPrefsConfigUi(self, valuesDict, userCancelled):
        if not userCancelled:
            self.debug = valuesDict.get("showDebugInfo", False)
            self.logMqtt = valuesDict.get("logMqtt", False)
            self.deviceFolderId = int(valuesDict.get("deviceFolder", 0))

            for dev in indigo.devices.iter("self.shellyController"):
                new_props = dev.pluginProps
                new_props["brokerHost"] = valuesDict.get("brokerHost", "localhost")
                new_props["brokerPort"] = valuesDict.get("brokerPort", "1883")
                new_props["mqttUsername"] = valuesDict.get("mqttUsername", "")
                new_props["mqttPassword"] = valuesDict.get("mqttPassword", "")
                new_props["rootTopic"] = valuesDict.get("rootTopic", "shellies")
                dev.replacePluginPropsOnServer(new_props)

                self._stop_coordinator(dev.id)
                dev = indigo.devices[dev.id]
                self._start_coordinator(dev)
                break

    # -------------------------------------------------------------------------
    # Auto-create coordinator
    # -------------------------------------------------------------------------

    def _create_coordinator_device(self):
        try:
            prefs = self.pluginPrefs
            props = {
                "brokerHost": prefs.get("brokerHost", "localhost"),
                "brokerPort": prefs.get("brokerPort", "1883"),
                "mqttUsername": prefs.get("mqttUsername", ""),
                "mqttPassword": prefs.get("mqttPassword", ""),
                "rootTopic": prefs.get("rootTopic", "shellies"),
            }
            create_kwargs = {
                "protocol": indigo.kProtocol.Plugin,
                "deviceTypeId": "shellyController",
                "name": "Shelly TRV",
                "props": props,
            }
            if self.deviceFolderId:
                create_kwargs["folder"] = self.deviceFolderId
            dev = indigo.device.create(**create_kwargs)
            dev.updateStateOnServer("mqttStatus", "disconnected")
            dev.updateStateImageOnServer(indigo.kStateImageSel.SensorOff)
            self.logger.info(f"Auto-created coordinator device: {dev.name}")
        except Exception as err:
            self.logger.error(f"Error creating coordinator device: {err}")

    # -------------------------------------------------------------------------
    # Auto-create child devices
    # -------------------------------------------------------------------------

    def _auto_create_device(self, coordinator_dev_id, equip_type, equip_id, equip_name):
        if equip_type not in DEVICE_TYPE_MAP:
            return

        device_type_id, id_prop_key = DEVICE_TYPE_MAP[equip_type]

        existing = self._find_child_device(coordinator_dev_id, device_type_id, id_prop_key, str(equip_id))
        if existing:
            return

        try:
            props = {
                "controllerId": str(coordinator_dev_id),
                id_prop_key: str(equip_id),
            }
            create_kwargs = {
                "protocol": indigo.kProtocol.Plugin,
                "deviceTypeId": device_type_id,
                "name": equip_name,
                "props": props,
            }
            if self.deviceFolderId:
                create_kwargs["folder"] = self.deviceFolderId
            new_dev = indigo.device.create(**create_kwargs)
            self.device_coordinator_map[new_dev.id] = coordinator_dev_id
            self.logger.info(f"Auto-created {equip_type} device: {equip_name} (ID {equip_id})")
        except Exception as err:
            self.logger.error(f"Error creating {equip_type} device '{equip_name}': {err}")

    # -------------------------------------------------------------------------
    # Coordinator management
    # -------------------------------------------------------------------------

    def _start_coordinator(self, dev):
        if not PAHO_AVAILABLE:
            self.logger.error("Cannot start coordinator — paho-mqtt not available")
            dev.updateStateOnServer("mqttStatus", "error")
            return

        dev_id = dev.id
        props = dev.pluginProps

        msg_queue = queue.Queue()
        thread = ThreadMqttHandler(
            dev_id=dev_id,
            broker_host=props.get("brokerHost", "localhost"),
            broker_port=props.get("brokerPort", 1883),
            username=props.get("mqttUsername", ""),
            password=props.get("mqttPassword", ""),
            root_topic=props.get("rootTopic", "shellies"),
            message_queue=msg_queue,
            logger=self.logger
        )

        self.coordinators[dev_id] = {
            "thread": thread,
            "queue": msg_queue,
            "root_topic": props.get("rootTopic", "shellies")
        }

        dev.updateStateOnServer("mqttStatus", "connecting")
        thread.start()
        self.logger.info(f"Starting MQTT connection for {dev.name}")

    def _stop_coordinator(self, dev_id):
        coord = self.coordinators.pop(dev_id, None)
        if coord and coord["thread"].is_alive():
            coord["thread"].stop()
            coord["thread"].join(timeout=5)

    # -------------------------------------------------------------------------
    # Message processing
    # -------------------------------------------------------------------------

    def _drain_queue(self, coordinator_dev_id, msg_queue):
        while not msg_queue.empty():
            try:
                msg = msg_queue.get_nowait()
            except queue.Empty:
                break

            msg_type = msg.get("type")

            if msg_type == "connection_status":
                self._handle_connection_status(msg)
            elif msg_type == "mqtt_message":
                self._handle_mqtt_message(coordinator_dev_id, msg)

    def _handle_connection_status(self, msg):
        dev_id = msg["dev_id"]
        status = msg["status"]
        try:
            dev = indigo.devices[dev_id]
            dev.updateStateOnServer("mqttStatus", status)
            if status == "connected":
                dev.updateStateImageOnServer(indigo.kStateImageSel.SensorOn)
            else:
                dev.updateStateImageOnServer(indigo.kStateImageSel.SensorOff)
        except KeyError:
            pass

    def _handle_mqtt_message(self, coordinator_dev_id, msg):
        topic = msg["topic"]
        topic_parts = msg["topic_parts"]
        payload = msg["payload"]

        if self.logMqtt:
            self.logger.debug(f"MQTT [{msg['sequence']}]: {topic} = {payload}")

        try:
            dev = indigo.devices[coordinator_dev_id]
            dev.updateStateOnServer("lastMessage", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        except KeyError:
            pass

        self._route_message(coordinator_dev_id, topic_parts, payload)

    def _route_message(self, coordinator_dev_id, topic_parts, payload):
        # Feed to discovery
        new_equip = self.discovery.process_message(coordinator_dev_id, topic_parts, payload)
        for equip in new_equip:
            self._auto_create_device(
                coordinator_dev_id, equip["type"], equip["id"], equip["name"]
            )

        # Route to thermostat handler
        thermostat_updates = thermostat_handler.process_thermostat_message(topic_parts, payload, self.logger)
        for equipment_id, state_updates in thermostat_updates:
            device = self._find_child_device(coordinator_dev_id, "shellyThermostat", "equipmentId", str(equipment_id))
            if device:
                device.updateStatesOnServer(state_updates)

        # Route to sensor handler
        sensor_updates = sensor_handler.process_sensor_message(topic_parts, payload, self.logger)
        for equipment_id, state_updates in sensor_updates:
            device = self._find_child_device(coordinator_dev_id, "shellySensor", "equipmentId", str(equipment_id))
            if device:
                device.updateStatesOnServer(state_updates)

    # -------------------------------------------------------------------------
    # Actions
    # -------------------------------------------------------------------------

    def thermostat_setSetpointHeat(self, pluginAction, dev, callerWaitingForResult):
        temperature = float(pluginAction.props.get("temperature", 70))
        equipment_id = dev.pluginProps.get("equipmentId")
        coordinator_id = self.device_coordinator_map.get(dev.id)

        if not equipment_id or not coordinator_id:
            self.logger.error(f"Missing equipment ID or coordinator for device {dev.name}")
            return

        payload = thermostat_handler.build_setpoint_payload(equipment_id, temperature)
        topic = f"{equipment_id}/settings"
        self._publish(coordinator_id, topic, payload)
        self.logger.info(f"Set thermostat {equipment_id} setpoint to {temperature}°F")

    def thermostat_setHvacMode(self, pluginAction, dev, callerWaitingForResult):
        mode = int(pluginAction.props.get("mode", indigo.kHvacMode.Off))
        equipment_id = dev.pluginProps.get("equipmentId")
        coordinator_id = self.device_coordinator_map.get(dev.id)

        if not equipment_id or not coordinator_id:
            self.logger.error(f"Missing equipment ID or coordinator for device {dev.name}")
            return

        payload = thermostat_handler.build_hvac_mode_payload(equipment_id, mode)
        topic = f"{equipment_id}/settings"
        self._publish(coordinator_id, topic, payload)

        mode_name = "Heat" if mode == indigo.kHvacMode.Heat else "Off"
        self.logger.info(f"Set thermostat {equipment_id} mode to {mode_name}")

    # -------------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------------

    def _find_child_device(self, coordinator_dev_id, device_type_id, prop_key, prop_value):
        for dev in indigo.devices.iter(f"self.{device_type_id}"):
            props = dev.pluginProps
            if (props.get("controllerId") == str(coordinator_dev_id) and
                    props.get(prop_key) == prop_value):
                return dev
        return None

    def getDeviceFolderList(self, filter="", valuesDict=None, typeId="", targetId=0):
        folder_list = [(0, "-- No Folder --")]
        for folder in indigo.devices.folders:
            folder_list.append((folder.id, folder.name))
        folder_list.sort(key=lambda x: x[1].lower() if x[0] != 0 else "")
        return folder_list

    def _publish(self, coordinator_dev_id, topic, payload):
        coord = self.coordinators.get(coordinator_dev_id)
        if coord:
            coord["thread"].publish(topic, payload)

    # -------------------------------------------------------------------------
    # Menu items
    # -------------------------------------------------------------------------

    def discoverEquipment(self):
        self.logger.info("Discovered equipment (devices are created automatically):")
        for dev_id in self.coordinators:
            try:
                dev = indigo.devices[dev_id]
                self.logger.info(f"Coordinator: {dev.name}")
                self.logger.info(self.discovery.get_summary(dev_id))
            except KeyError:
                pass